---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "16"
    ansible_distribution_release: "Hirsute" #trusty
  tasks:
    - name: Download setup filee
      get_url:
        url: "https://deb.nodesource.com/setup_lts.x"
        dest: "~/Downloads"

    - name: "Run the setup file"
      command: "sudo bash ~/Downloads/setup_lts.x"
      no_log: true

    - name: "Install node"
      apt:
        name: nodejs
        state: latest
        update_cache: true

    - name: delete file at after the install
      file:
        path: "~/Downloads/setup_lts.x"
        state: absent


#    - name: Install the nodejs
#      apt:
#        name: nodejs
#        state: present
